### ISSUE TITLE
Tippfehler

### ISSUE THREAD

**Issue by jschoenbohm** [protrain/protrain.github.io#1]
Kapitel 1.5 Seite 5 unten
Selbiges gilt für **LÖs**ungen in anderen Programmiersprachen

**Comment by wiefling** [comment]
Hallo jschoenbohm,
leider sind wir jetzt erst auf das GitHub-Issue aufmerksam geworden. Danke für das Melden des Fehlers, werden wir auf unserer Errata-Seite einbauen.
